# Permalinks
permalink:        pretty

# Setup
title:            Archery Engine
tagline:          ''
description:      'Control Panel and Visual Editor of the Archery Cloud Platform.'
url:              http://archery.ntr1x.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ntr1x/ntr1x.github.io
